name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Code Coverage
      run: sudo apt-get install -y kcov && cargo install cargo-kcov && cargo kcov && bash <(curl -s https://codecov.io/bash) -f target/cov/index.html && echo "Uploaded code coverage"
