name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
  codecov:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Code Coverage
      run: |
        sudo apt-get update && sudo apt-get install kcov -y
        kcov --version
        cargo build
        pwd
        ls -l
        ls -l target/debug/gen_gcode-*
        for file in target/debug/gen_gcode-*; do echo $file; mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"